version: '3.5'
services:
  csgo:
    build: .
    env_file:
      - .env
    ports:
      - 27015:27015/tcp
      - 27015:27015/udp
      - 27020:27020/udp
    restart: unless-stopped
    user: csgo
    volumes:
      - ./srv:/srv
